### PR TITLE
Google trans multilingual

### PR DESCRIPTION
**Pull request by TarifEzaz**
Translations for xnli and paws-x dataset has been added.

### CODE REVIEW

**Comment by sbmaruf** [comment]
Thanks a lot!
I will review the pull request. Also trying to find someone to review arabic.
Did you solve the Vietnamese translation issue?

**Comment by TarifEzaz** [comment]
Vietnamese translation did not have any issues. Probably you are mentioning the thai language issue. It has been fixed. Along with arabic, can you please ask someone to review the Urdu language as well? It has the same scenario of writing from right to left.

**Comment by sbmaruf** [comment]
@TarifEzaz  Thanks a lot for clarifying. Did you use google translator for thai or some other translator?

**Comment by TarifEzaz** [comment]
@sbmaruf : We've used Google translator, but the option for Thai language is not in the dropdown list. We had to google it to get the translator form.

**Comment by sbmaruf** [comment]
I can see the translation option here. https://translate.google.com/?sl=en&tl=th&text=Hello%20world&op=translate
Is there any geo block?

**Comment by TarifEzaz** [comment]
I see. Not sure about the geographic issue.

**Comment by KhalidAlt** [comment]
Hi @sbmaruf and @TarifEzaz, I have looked into both Arabic  and Urdu  and the 'right-to-left' alignment seems correct to me. Please let me know if I can help in anything else. Thanks

**Comment by TarifEzaz** [comment]
Thank you @KhalidAlt

**Comment by TarifEzaz** [comment]
I have added translations for xquad dataset as well. Please have a look @sbmaruf

**Pull request merged**
